default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: database_dev

test:
  <<: *default
  database: database_test
  
staging:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'your_staging_db') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'your_prod_db') %>
